### PR TITLE
One step closer to having a working nginx configuration

### PR DESCRIPTION
**Pull request by Psycojoker**
Hello,

I'm trying to make this app works and locally this seems to be the trick to make nginx happy (at least for showing the website, I haven't tested other things yet).

Kind regards,

### CODE REVIEW

**Comment by opi** [comment]
Looks good to me

**Comment by anaqreon** [comment]
So is all the fast-cgi stuff unnecessary here?

**Comment by julienmalik** [comment]
Yes this only makes sense if the source code is written in PHP

**Comment by Psycojoker** [comment]
@julienmalik I've installed the app using "/" as the path and it worked fine. Are you talking about the case where the path == ""? If so, shouldn't it be defaulted to "/" in yunohost? cc @opi

**Comment by Psycojoker** [comment]
Btw, the app seems to be working fine with this configuration, not bugs to report yet (but I haven't used it extensively and I don't know the expected behaviour).

**Comment by julienmalik** [comment]
it's just that usually we only use alias, not root.
so i was suggesting a hint to make it work with alias, when path='/'.

i recently fixed 2 of my apps to cover this.

in the current situation (without this PR), i bet the app does not work when installed on root of subdomain, with path="/" (403 forbidden)

**Comment by julienmalik** [comment]
See https://github.com/julienmalik/agendav_ynh/commit/dcda7bb40bd291fa69d97215f3c65b38e74bbdf3
and
https://github.com/julienmalik/baikal_ynh/commit/86ab487397d27848c637ac3a1950dfc76271eb74

**Comment by julienmalik** [comment]
Actually, cf http://stackoverflow.com/questions/10631933/nginx-static-file-serving-confusion-with-root-alias
the root directive does need to be changed to alias.
Otherwise the app will not be installable in subdir.

**Comment by Psycojoker** [comment]
@julienmalik fixed following your instructions (I've also tested it on my local installation and it works as expected).

**Pull request merged**
